# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-11-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='button_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_tutorial.ButtonHistory'),
        ),
    ]
